apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone-project-deployment
  template:
    metadata:
      labels:
        app: capstone-project-deployment
    spec:
      containers:
        - name: capstone-project-deployment
          image: sarahlyne46/capstone-project:greenv2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-deployment
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
